name: ${pluginName}
main: com.biggestnerd.namecolors.NameColors
version: ${version}
authors: [biggestnerd, Maxopoly]
depend: [CivModCore, CivChat2]
softdepend:
  - TAB
description: ${description}
api-version: ${api_version}
commands:
  namecolor:
    description: "Give your name a nice color!"
    usage: "Usage /namecolor"
    permission: namecolor.use
permissions:
  namecolor.use:
    description: Allows you to change the color of your name
    default: op
  namecolor.rainbow:
    description: Lets you get a rainbow name
    default: op